spring:
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    